### ISSUE TITLE
Error when updating bandwidth under Harvest Configuration

### ISSUE THREAD

**Issue by calvinSTF** [DIA-NZ/webcurator#10]
Hi,

I recently test run version 1.6.2 and facing some issues. One of the issue is that I am getting NullPointer Error whenever I updating the Harvest Configuration > Bandwidth. Mind helping me troubleshoot this problem ?
[wct-core..txt](https://github.com/DIA-NZ/webcurator/files/813356/wct-core.txt)

**Comment by obrienben** [comment]
Hi,
Sure, was this a fresh install or an upgrade from 1.6.1 or 1.6.0? And does the HEATMAP_CONFIG table exist in your db? 

Cheers,
Ben

**Comment by calvinSTF** [comment]
Hi obrienben,

It is a fresh install of version 1.6.2. The HEATMAP_CONFIG table do exist. I attach here with my DB in mysql. Also note that I remember manually adding some of the extra field that was missing from the original sql file from Github according to the Data Dictionary pdf to solve a lot of the java error on missing field issue.
[calvin_db_wct.sql.txt](https://github.com/DIA-NZ/webcurator/files/815474/calvin_db_wct.sql.txt)

**Comment by obrienben** [comment]
Hi Calvin,

Looking at the database dump you attached, there is no data in the HEATMAP_CONFIG table. At the least there should be three rows which get added from the following file during setup [https://github.com/DIA-NZ/webcurator/blob/master/wct-core/db/upgrade/upgrade-mysql-1_6-to-1_6_1.sql](url).

Can you try renaming your database and re-creating a new one, and running the following scripts, in this order (assuming mysql):

1. wct-core/db/setup/mysql-create-wct.sql

1.  wct-core/db/sql/wct-schema-1_6-mysql.sql

1. wct-core/db/sq/wct-indexes-1_6-mysql.sql

1. wct-core/db/sql/wct-mysql-bootstrap.sql

1. wct-core/db/sql/wct-qa-data-1_6-mysql.sql

1. wct-core/db/upgrade/upgrade-mysql-1_6-to-1_6_1.sql

1. wct-core/db/sql/wct-schema-grants-1_6_1-mysql.sql

Which setup scripts to run has needed better clarity for a while now in the documentation

**Comment by calvinSTF** [comment]
Hi obrienben,

Thanks for the walkthrough. The error no longer appears.
