### ISSUE TITLE
Reduce size of release

### ISSUE THREAD

**Issue by sepastian** [DIA-NZ/webcurator#107]
Hello, first things first: thanks for webcurator.

I'm in the process of building a Docker image for webcurator tool.

I have notice that the releases, for example https://github.com/DIA-NZ/webcurator/archive/v2.0.1.tar.gz contains a number of large files that probably should not be part of the release. When building and testing a `Dockerfile`, the release will be downloaded many times, which is why i began to wonder and investigate why 2.0.1 is 268 MB in size.

Without knowing much about webcurator, would it be possible to remove these files:

```
wct-core/etc/photoshop # > 50 MB
docs # ~ 100 MB
src/test # > 30 MB
```

These three would cut down the size of the release by 180 MB. There are probably more files and directories not required for running webcurator.

What do you think?

**Comment by kurtlenfesty** [comment]
Hi Sebastian - thanks for the support of webcurator.

You're quite right about the large files in the github repository that make downloading the repository an issue in terms of bandwidth and size.

It's something that we identified as an issue a few months ago.

Part of what we're working on this year is splitting up the Web Curator Tool into multiple components, each with its own repository. So the files in docs and photoshop, for example, have been moved to their own repositories.

You can view those repositories at https://github.com/WebCuratorTool. This will be source for version 3.0, which we're hoping to have available in June. If you look at the WebCuratorTool repositories you can see that photoshop has been split out into webcurator-legacy-photoshop and the legacy docs (not the new readthedocs) has been split out into webcurator-legacy-docs. The readthedocs documentation is now in webcurator-docs.

All the code up to version 2.0.1 has been migrated to these new repositories and I'll be merging in the 2.0.2 changes in the next few days.

I wouldn't recommend using these repositories for your docker builds at the moment. I think it would involve too much fiddling, as there was work done to change the maven builds to work independently and there hasn't been work done yet to get them all working as part of a build pipeline.

We are planning to dockerise the Web Curator Tool this year after 3.0 is released -- that is our long term goal. I'm hoping to produce an AWS CloudFormation template for docker in the next few months as well.

I'm planning to have versions of these new Web Curator Tool repositories ready for @obrienben and @hannakoppelaar to work with within a couple of weeks, depending on how quickly I progress to upgrading Spring, Hibernate and moving the code to use Spring Boot.

I'll try to keep you in mind when I have something that you can try out. However, if you're wanting to run Web Curator Tool in docker containers in production in the next couple of months, then you'll need to stick with 2.x and deal with the issues you've already encountered with the large repository size.

I hope this helps you with what you're trying to do,
Kurt

**Comment by sepastian** [comment]
Thanks for the reply @kurtlenfesty. i have forked 2.x, added `.gitattributes` and created a smaller release.

I can now `mvn install -DskipTests` (building with tests doesn't work for some reason) and end up with 4 war files.

```
$ find -name '*.war'
./wct-store/target/wct-store.war
./harvest-agent-h1/target/harvest-agent-h1.war
./harvest-agent-h3/target/harvest-agent-h3.war
./wct-core/target/wct.war
```

Are these all files required to run the app in Tomcat? The documentation seems a bit out-of-date on this.

**Comment by kurtlenfesty** [comment]
Yes, that's how I run my test setup. There's also the wayback integration.

In terms of documentation, are you referring to https://webcuratortool.readthedocs.io/en/latest/?

When you say "out-of-date", can you be a bit more specific? Our plan was to have comprehensive and complete documentation for the 2.0 release, so if there's something that we've missed it would be helpful to know what that is.

**Comment by sepastian** [comment]
Should there be a `war` file for the wayback integration? Where? I didn't get one. :thinking: 

Yes, that one. For example, in _Quick Start_ it says

```
user@host:/tmp/wct$ cd db
user@host:/tmp/wct/db$ ./set-up-mysql.sh
```

But that directory doesn't exist. `cd db` should be `cd wct-core/db`.

Also, where exactly are these binary releases located?

**Comment by kurtlenfesty** [comment]
Releases are found here: https://github.com/DIA-NZ/webcurator/releases (or from the 'releases' tab of https://github.com/DIA-NZ/webcurator).

That's good that you've found errors in our documentation. I'm not sure what our process is to aggregate documentation corrections. I'll try and chat with @obrienben and @hannakoppelaar later today to see if we have a place to collect documentation errata or some other way of tracking small corrections. Or maybe just the github way, which is to create a branch with a few corrections and then a pull request to merge in the fix.

**Comment by sepastian** [comment]
So the most recent binary release would be 1.6.2? Will there be a binary release for 2.x, so I could skip the build step?

Sorry for all these questions. But I can create a PR for documentation.

**Comment by kurtlenfesty** [comment]
The wct-v2.0 GA binary is there, can you not see it?

As for Wayback Integration, see https://webcuratortool.readthedocs.io/en/latest/guides/wayback-integration-guide.html for all the details.

One of the things that Ben noted is that it's really easy to find stuff using readthedocs. If you're having trouble getting your questions answered in the documentation then we need to improve our documentation. But the wayback integration was easy to find in readthedocs, so I'm not sure why you were asking about where the war file is for the wayback integration. Is the documentation not clear about how to get it set up?

**Comment by sepastian** [comment]
I expected that the build process would yield a war file for _integrating wayback somehow_. That's not the case, I will check the documentation on that, thanks.

As for the binary 2.0 release: no, I can't see that. 1.6.3 is the latest release; 1.7.3 is tagged with pre-release; there's no release for 2.x, only tags for 2.0.0 and 2.0.1 - both of which contain sources only.

**Comment by hannakoppelaar** [comment]
@sepastian, @kurtlenfesty It seems the 2.0 GA bin release still has the draft status and is only visible to admins (or contributors?) of the repo. So it's there, but not publicly accessible yet. I guess this is just an oversight on our part? Or is there another reason it hasn't been published yet?

The Quick Start Guide assumes the directory layout of the bin release, which differs slightly from the source release, hence the different directory name. This makes it all the more pertinent to put up a bin release.

**Comment by sepastian** [comment]
Could you release 2.x please, that would be great!

**Comment by kurtlenfesty** [comment]
The wct-v2.0 GA release should be visible now.

**Comment by sepastian** [comment]
Thanks and thanks for answering my questions. I will let you know about the Docker build for 2.x, looking forward to your 3.x Docker build.
