### ISSUE TITLE
Target instance hangs in Stopping state

### ISSUE THREAD

**Issue by hannakoppelaar** [DIA-NZ/webcurator#109]
I noticed that sometimes a target instance can get stuck in the Stopping state. It seems this is due to a null pointer exception that gets thrown when the corresponding Heritrix job directory does not contain an expected subdirectory, such as "warcs" or "reports". This runtime exception leads to the bookkeeping routine (_HarvestCompleteJob.execute()_) being rescheduled, leaving the instance in the Stopping state. 

Would it make sense to replace the null pointer exception with an empty array return value? Then the target instance would move to its next state, Harvested, resulting in a target instance with 0 warcs or 0 reports, respectively.

**Comment by obrienben** [comment]
@hannakoppelaar in the cases you observed, what folders were missing? Were 'warcs' and 'reports' both missing? Was that a case of the harvest not actually starting?

**Comment by hannakoppelaar** [comment]
@obrienben I've only been able to reproduce it with harvests that contain non-existent seeds, so no warc file gets written. Then when you stop such a harvest, it will remain forever 'Stopping'. 

Unfortunately, I've just found a harvest that does have all those subdirectories and a warc file, but is still hanging in the stopping state, so the analysis of this issue is incomplete.

**Comment by hannakoppelaar** [comment]
Closing this issue. I've opened a new issue, #112, for clarity.
