### ISSUE TITLE
custom beans do not make it from defaultH3Profile.cxml into the heritrix 3 job config xml

### ISSUE THREAD

**Issue by vitezg** [DIA-NZ/webcurator#110]
After adding 
`<bean id="historyBdb" class="org.archive.bdb.BdbModule" autowire-candidate="false">
<property name="dir" value="/var/local/wct/heritrix-dedup-db" />
</bean>
<bean id="contentDigestHistory" class="org.archive.modules.recrawl.BdbContentDigestHistory">
 <property name="bdbModule">
  <ref bean="historyBdb" />
 </property>
</bean>`

either to tomcat8/webapps/wct/WEB-INF/classes/defaultH3Profile.cxml or in the source to harvest-agent-h3/build/defaultH3Profile.cxml and recompiling, the beans do not make it into the newly created heritrix 3 job configuration xmls.

Could this be an oversight on our part or does wct cut out the unknown parts from  defaultH3profile.cxml? 

The same configuration works well when fed directly to heritrix.

We'd like to set up global deduplication for every job we start from WCT, and so far this was the only possibility we found.

**Comment by hannakoppelaar** [comment]
In my setup, if I add your bean to tomcat8/webapps/wct/WEB-INF/classes/defaultH3Profile.cxml it does get added to any newly created profiles (via Management->profile->create new). The existing profiles remain unaltered though, which is as designed, I guess.

If you want to add it at build time, I think you need to add it to wct-core/src/main/resources/defaultH3Profile.cxml. I don't think the profiles in the harvest-agent-h3 module serve any purpose and we should probably get rid of them.

**Comment by vitezg** [comment]
Thanks, the error was on our side, we missed the Management->profile->create new step. It works now.

I only wanted to do this at build time because it's in the documentation: https://webcuratortool.readthedocs.io/en/latest/guides/system-administrator-guide.html#default-profile

**Comment by hannakoppelaar** [comment]
Great! And thanks for pointing me to the docs. We'll definitely need to remove one of those included default profiles, for clarity.
