### ISSUE TITLE
The Administrator guide is missing 

### ISSUE THREAD

**Issue by suxonca** [DIA-NZ/webcurator#12]
Hi ,
 I know that this is in Sourceforce but the wiki of Github need a link.

Thanks.

**Comment by obrienben** [comment]
Hi there, 
are you saying the front page of the wiki needs a link to it? Because there are links to the System Admin guide under documentation https://github.com/DIA-NZ/webcurator/wiki/Documentation. Although I see there is no System Admin guide link for v1.6 under documentation.

**Comment by suxonca** [comment]
Hi, Thanks for your anwser.. 
yes exactly, I didn't see the link at first view, Then I went to the sourceforce page, It will be nice have it in the front page. 
thanks a lot.
