### ISSUE TITLE
D1.1 Move H3 implementation into its own Harvest Agent

### ISSUE THREAD

**Issue by hannakoppelaar** [DIA-NZ/webcurator#18]
Separate old Heritrix and H3 Harvest Agent code into different modules. The Harvest Agents can be preconfigured to a specific crawler. Abstract out a common library of the Harvest Agent base classes/interfaces for quicker building of new Harvest Agent types.

Subtasks:
* Duplicate the Harvest Agent Module and revert it back to original.
* Build base Harvest Agent library for new Harvest Agents to extend.
* Modify H3 Harvest Agent to use Harvest Agent base library.

**Comment by obrienben** [comment]
I started to extract out classes for a base harvest agent library, but found too many dependencies in Core. For instance the HarvestAgent interface with is used by both sides for communicating, and located in Core, is used by harvest agent via the maven wct-core dependency. Another being the DTO classes.
Perhaps, further down the line, a better alternative might be to extract out these common classes across the entire project into a common/core module.
For this story I'll just stick to moving the different harvester implementations (H1 and H3) into separate harvest agents.

**Comment by obrienben** [comment]
Main change I've made for this story is making the harvest agent web service name configurable. Previously it was hard coded within Core to "/wct-harvest-agent/services/urn:HarvestAgent". Now the harvest agent webapp can be renamed, eg. "harvest-agent-h3".

**Comment by hannakoppelaar** [comment]
Closing this, as the feature branch has been merged.
