### ISSUE TITLE
Adding resources to harvest in Tree View doesn't work

### ISSUE THREAD

**Issue by hannakoppelaar** [DIA-NZ/webcurator#23]
Either from a URL or from disk. I always get an error: "java.io.FileNotFoundException: /wct/store/uploadedFiles/&lt;some uuid&gt; (No such file or directory)". Or is this a local config error?

**Comment by obrienben** [comment]
I think its a local config problem, or file/folder permissions. Check that dir path /wct/store/uploadedFiles exists and WCT can write to it

**Comment by hannakoppelaar** [comment]
You're right, it was configuration problem.

**Comment by obrienben** [comment]
What was the fix?

**Comment by hannakoppelaar** [comment]
The paths in wct-das.properties were wrong.
