### ISSUE TITLE
D1.4.6 H3 profile import functionality

### ISSUE THREAD

**Issue by obrienben** [DIA-NZ/webcurator#38]
Profile import functionality to handle H3 profiles.
This should also include validation of the H3 profile, using an H3 instance, H3 libraries, or some other means.

**Comment by hannakoppelaar** [comment]
@obrienben Okay, this is interesting. There's no utility in the H3 codebase for validating a profile ("crawler-beans configuration"). H3 relies on validation of the corresponding beans by Spring. It only checks the XML for well-formedness. We could tap into the validation functionality indirectly by doing something like this:


        CrawlJob cj = new CrawlJob(new File("/tmp/test.cxml"));

        cj.instantiateContainer();

        if (cj.hasApplicationContext()) {
        	System.out.println("Profile looks OK");
        } else {
        	System.out.println("Profile does not seem to be valid");
        }

But then we'd be tying ourselves to Heritrix APIs that we can hardly consider public and stable. Using the REST-API for validating doesn't look too promising either. Perhaps we should just write our own well-formedness check with a few basic sanity checks added in? One example of such a sanity check could be validating against the Spring beans schemas.

**Comment by obrienben** [comment]
Closed by PR #41
