### ISSUE TITLE
Consistent naming for SQL files.

### ISSUE THREAD

**Issue by renevoorburg** [DIA-NZ/webcurator#43]
The sql files needed for installing WCT all have filenames that include the name of the database (mysql, etc.). The wct-schema-grants.sql file is an exception, this one is used for both oracle and postgresql.
It would make the  install more clear if we used alwats added the database name to the .sql files. So I propose to duplicate the wct-schema-grants.sql file to both wct-schema-grants-oracle and wct-schema-grants-postgresql.sql (schema-grants-mysql.sql already exists).

**Comment by obrienben** [comment]
Resolved in commit 0c0549ae3a580506b2447ae89b359d44e3344d36
