### ISSUE TITLE
D1.6 Harvest Scheduler harvester-type

### ISSUE THREAD

**Issue by hannakoppelaar** [DIA-NZ/webcurator#45]
Harvest scheduling needs to check the harvester-type of a Target Instance. Harvests need to be assigned to a Harvest Agent of the same harvester-type:

* Check Target Instance harvester-type and assign to correct Harvest Agent
* Show Harvest Agents of correct harvester-type in 'Harvest Now'

**Comment by hannakoppelaar** [comment]
I considered checking if a harvester of the required type is available as soon as you tick 'Harvest Now' and click 'Save', but I'm not convinced it's a good idea. A harvester might become available by the time the scheduled job is actually run. For now I'm leaving this out.

So what I have now is:
* when a harvest is queued (in HarvestCoordinatorImpl) we only try to allocate it to a harvest agent of the correct type;
* when you start a target instance manually (on the queue page) after having created it using 'Harvest Now', you only get to see harvest agents of the correct type to which you can allocate the harvest.

**Comment by obrienben** [comment]
Closed by PR #46
