### ISSUE TITLE
D1.4.6.2 Editor for overrides of imported profiles

### ISSUE THREAD

**Issue by hannakoppelaar** [DIA-NZ/webcurator#51]
Under the Profile tab in the Target screen the user can override certain configuration options in the profile. This only works for profiles created by WCT. For imported profiles we will add the option to edit the raw XML, which will then be stored at the target level and completely override the profile that was originally selected for this target.

**Comment by kurtlenfesty** [comment]
I've corrected the annotation on ProfileOverrides.java#getH3RawProfile and pushed that change into your branch. It affects how H2 creates the database (otherwise the field is VARCHAR in H2).

**Comment by obrienben** [comment]
Closed by PR #54
