### ISSUE TITLE
LogReader failing in WCT-Store

### ISSUE THREAD

**Issue by obrienben** [DIA-NZ/webcurator#57]
This bug was introduced after #20 
By removing the aheritrix dependency from wct-store, viewing the crawl logs fails for completed harvests.
`org.webcurator.core.exceptions.WCTRuntimeException: Failed to invoke tail on the SOAP service : java.lang.reflect.InvocationTargetException`

This is due to wct-store's use of LogReaderImpl in the wct-core dependency, which is why the build of wct-store is still successful. For instance, the tail method in LogReaderImpl invokes _org.archive.crawler.util.LogReader.tail()_ (line 71).

After a quick look, I can't see a replacement method within the webarchive-commons lib for the log reader calls. So I'm not sure whether it is worth the effort (and possible) now to try and shift all the remaining aheritrix dependent calls in wct-core to use webarchive-commons or an equivalent, or just allow the aheritrix dependency back into wct-store and park the issue for now.

**Comment by hannakoppelaar** [comment]
That would fix this problem for now, but didn't the inclusion of aheritrix.jar in wct-store lead to conflicts on your side?

Alternatively we could take these old aheritrix methods dealing with log file i/o and put them in a Utils class of our own.
