### ISSUE TITLE
Make profile override option for robots match profile management

### ISSUE THREAD

**Issue by obrienben** [DIA-NZ/webcurator#59]
The ui field for 'Ignore Robots' in H3 profile overrides for a Target don't match the ui in the main profile management.

Profile override
![image](https://user-images.githubusercontent.com/5760612/47116842-47ccf100-d2bf-11e8-91f0-dd3dadf0c4c5.png)

Main profile management
![image](https://user-images.githubusercontent.com/5760612/47116911-74810880-d2bf-11e8-814d-c1dcdd54fca7.png)

Change the profile override screen to use the checkbox. The checkbox is simpler and less ambiguous.

**Comment by hannakoppelaar** [comment]
Fix has been merged.
