### ISSUE TITLE
Emails may only have TLDs with at most 4 characters

### ISSUE THREAD

**Issue by bitzl** [DIA-NZ/webcurator#7]
With new TLDs like *.museum*, it is possible to have Email addresses with an TLD longer than 4 characters:

    example@skd.museum

The TLD is restricted in [ValidatorUtil](https://github.com/DIA-NZ/webcurator/blob/65f436d7cbd24bf8bb2af9538418f5922bd0f01a/wct-core/src/main/java/org/webcurator/ui/common/validation/ValidatorUtil.java#L51-L52
) to 4 letters:

```java
public final static String EMAIL_VALIDATION_REGEX = "^[_a-zA-Z0-9-]+(\\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)*(\\.[a-zA-Z]{2,4})$";
``` 

To fix this, set the last number to something larger, like

```java
public final static String EMAIL_VALIDATION_REGEX = "^[_a-zA-Z0-9-]+(\\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)*(\\.[a-zA-Z]{2,10})$";
```

**Comment by obrienben** [comment]
Resolved by PR #47
