### ISSUE TITLE
Drools exceptions in QA module

### ISSUE THREAD

**Issue by hannakoppelaar** [DIA-NZ/webcurator#90]
When the automated QA tests run after a harvest has finished, exceptions appear in the log: apparently the classes compiled by Drools are invalid. This might be a JDK8 compatibility issue.

What to look for:

_2018-12-27 16:09:22,873 INFO  [http-nio-8080-exec-141] rules.QaRecommendationServiceImpl (QaRecommendationServiceImpl.java:105) - Loading rules file rules.drl
**** COMPILER BUG! REPORT THIS IMMEDIATELY AT http://jira.codehaus.org/browse/mvel2_

And:
  
_java.lang.VerifyError: (class: ASMAccessorImpl_15846973001545923363520, method:   getKnownEgressType signature: ()Ljava/lang/Class;) Illegal type in constant pool
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.newInstance(Class.java:412)_

**Comment by kurtlenfesty** [comment]
I'm looking at this at the moment. I've needed to upgrade a bunch of jars to avoid this issue. I'm testing my fix and will reference the branch when I push it up.

**Comment by kurtlenfesty** [comment]
Branch pushed up for testing: https://github.com/DIA-NZ/webcurator/compare/replace-jboss-soap-with-latest-jaxws-rt?expand=1

**Comment by hannakoppelaar** [comment]
This issue seems to be fixed in that branch. Good work!

**Comment by kurtlenfesty** [comment]
I'm just waiting for Ben to put this into UAT to verify that it all works. When it's verified I'll create a pull request for the master branch.

**Comment by kurtlenfesty** [comment]
Pull request: https://github.com/DIA-NZ/webcurator/pull/94

**Comment by kurtlenfesty** [comment]
Resolved by https://github.com/DIA-NZ/webcurator/pull/98
